"""test

Revision ID: 770364ba713e
Revises: 879cd1fdd389
Create Date: 2026-06-09 08:02:39.770415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770364ba713e'
down_revision: Union[str, Sequence[str], None] = '879cd1fdd389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=False),
    sa.Column('style', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('node_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('object_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('object_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['object_type.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('object_kind',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['object_kind.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['type_id'], ['object_type.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('object',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kind_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('x_cord', sa.Float(), nullable=True),
    sa.Column('y_cord', sa.Float(), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('plan_link', sa.Text(), nullable=True),
    sa.Column('blueprint_link', sa.Text(), nullable=True),
    sa.Column('scale', sa.Text(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('SVG', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kind_id'], ['object_kind.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['parent_id'], ['object.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['state_id'], ['object_state.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('short_name'),
    sa.UniqueConstraint('x_cord'),
    sa.UniqueConstraint('y_cord')
    )
    op.create_table('connection_object',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id1', sa.Integer(), nullable=False),
    sa.Column('object_id2', sa.Integer(), nullable=False),
    sa.Column('connection_type_id', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['connection_type_id'], ['connection_type.id'], ),
    sa.ForeignKeyConstraint(['object_id1'], ['object.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['object_id2'], ['object.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('SVG', sa.Text(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['parent_id'], ['node.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['type_id'], ['node_type.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('connection_node',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id1', sa.Integer(), nullable=False),
    sa.Column('node_id2', sa.Integer(), nullable=False),
    sa.Column('connection_type_id', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['connection_type_id'], ['connection_type.id'], ),
    sa.ForeignKeyConstraint(['node_id1'], ['node.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['node_id2'], ['node.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_node')
    op.drop_table('node')
    op.drop_table('connection_object')
    op.drop_table('object')
    op.drop_table('object_kind')
    op.drop_table('object_type')
    op.drop_table('object_state')
    op.drop_table('node_type')
    op.drop_table('connection_type')
    # ### end Alembic commands ###
