"""cord upd

Revision ID: 82e246fcf79e
Revises: 770364ba713e
Create Date: 2026-06-09 08:51:14.825178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e246fcf79e'
down_revision: Union[str, Sequence[str], None] = '770364ba713e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('object_x_cord_key'), 'object', type_='unique')
    op.drop_constraint(op.f('object_y_cord_key'), 'object', type_='unique')
    op.drop_column('object', 'x_cord')
    op.drop_column('object', 'y_cord')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('y_cord', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('object', sa.Column('x_cord', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('object_y_cord_key'), 'object', ['y_cord'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('object_x_cord_key'), 'object', ['x_cord'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
