"""node parent removal

Revision ID: d0e5e6991e3c
Revises: 82e246fcf79e
Create Date: 2026-06-09 10:44:29.998492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e5e6991e3c'
down_revision: Union[str, Sequence[str], None] = '82e246fcf79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('node_parent_id_fkey'), 'node', type_='foreignkey')
    op.drop_column('node', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('node_parent_id_fkey'), 'node', 'node', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
